spring:
  application:
  name: smartdelivery

  datasource:
    url: jdbc:postgresql://localhost:5432/smartdelivery
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  rabbitmq:
    addresses: amqps://yrhrcbif:kRsJHMJ44ateNHEEdG-bKgqPN1kcPAT5@shrimp.rmq.cloudamqp.com/yrhrcbif
    username: yrhrcbif
    password: kRsJHMJ44ateNHEEdG-bKgqPN1kcPAT5
    virtual-host: yrhrcbif
